# Generated by Django 4.2.1 on 2023-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left_heading", models.TextField()),
                ("left_description", models.TextField()),
                ("left_logo", models.ImageField(upload_to="")),
                ("right_heading", models.TextField()),
                ("right_description", models.TextField()),
                ("right_logo", models.ImageField(upload_to="")),
            ],
        ),
    ]
