# Generated by Django 4.2.1 on 2023-06-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="left_logo",
            field=models.ImageField(upload_to="technology/"),
        ),
        migrations.AlterField(
            model_name="technology",
            name="right_logo",
            field=models.ImageField(upload_to="technology/"),
        ),
    ]
