# Generated by Django 4.2.1 on 2023-06-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_technology_left_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description1", models.TextField()),
                ("description2", models.TextField()),
                ("description3", models.TextField()),
                ("description4", models.TextField()),
                ("description5", models.TextField()),
                ("description6", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributesName1", models.CharField(max_length=80)),
                ("attributes1", models.TextField()),
                ("attributesName2", models.CharField(max_length=80)),
                ("attributes2", models.TextField()),
                ("attributesName3", models.CharField(max_length=80)),
                ("attributes3", models.TextField()),
                ("attributesName4", models.CharField(max_length=80)),
                ("attributes4", models.TextField()),
                ("attributesName5", models.CharField(max_length=80)),
                ("attributes5", models.TextField()),
                ("attributesName6", models.CharField(max_length=80)),
                ("attributes6", models.TextField()),
                ("attributesName7", models.CharField(max_length=80)),
                ("attributes7", models.TextField()),
                ("attributesName8", models.CharField(max_length=80)),
                ("attributes8", models.TextField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.collection",
                    ),
                ),
            ],
        ),
    ]
