# Generated by Django 4.2.1 on 2023-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_collection_name_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="description1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description6",
            field=models.TextField(blank=True, null=True),
        ),
    ]
