# Generated by Django 4.2.1 on 2023-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_product_attributes1_alter_product_attributes2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="left_logo",
            field=models.ImageField(upload_to="shop/static/technology/"),
        ),
        migrations.AlterField(
            model_name="technology",
            name="right_logo",
            field=models.ImageField(upload_to="shop/static/technology/"),
        ),
    ]
