# Generated by Django 4.2.1 on 2023-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_alter_technology_left_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="left_logo",
            field=models.ImageField(upload_to="shop/images/"),
        ),
        migrations.AlterField(
            model_name="technology",
            name="right_logo",
            field=models.ImageField(upload_to="shop/images/"),
        ),
    ]
