# Generated by Django 4.2.1 on 2023-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_technology_left_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="desc",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
