# Generated by Django 4.2.1 on 2023-06-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_product_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="total",
            field=models.TextField(blank=True, default=""),
        ),
    ]
