# Generated by Django 4.2.1 on 2023-06-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_contact_us_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner_Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(default="")),
            ],
        ),
    ]
