# Generated by Django 4.2.1 on 2023-06-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_owner_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact_us_text",
            old_name="pop_up",
            new_name="failure_msg",
        ),
        migrations.AddField(
            model_name="contact_us_text",
            name="success_msg",
            field=models.TextField(default=""),
        ),
    ]
