# Generated by Django 4.2.1 on 2023-06-16 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_faqs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="faqs",
            new_name="FAQ",
        ),
    ]
