# Generated by Django 4.2.1 on 2023-06-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_rename_faqs_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="heading",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
