# Generated by Django 4.2.1 on 2023-06-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_collection_heading"),
    ]

    operations = [
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("url", models.TextField()),
                ("desc", models.TextField()),
            ],
        ),
    ]
